<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-libraries" data-toc-modified-id="Import-libraries-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import libraries</a></span></li><li><span><a href="#Read-Data" data-toc-modified-id="Read-Data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Read Data</a></span></li><li><span><a href="#Check-info-and-descriptive-stats" data-toc-modified-id="Check-info-and-descriptive-stats-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Check info and descriptive stats</a></span></li><li><span><a href="#Cleaning" data-toc-modified-id="Cleaning-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Cleaning</a></span><ul class="toc-item"><li><span><a href="#Drop-extra-rows-and-clean-null-values" data-toc-modified-id="Drop-extra-rows-and-clean-null-values-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Drop extra rows and clean null values</a></span></li><li><span><a href="#Clean-Population-data" data-toc-modified-id="Clean-Population-data-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Clean Population data</a></span></li><li><span><a href="#Data-type-cleaning" data-toc-modified-id="Data-type-cleaning-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Data type cleaning</a></span></li><li><span><a href="#Dropping-extra-rows" data-toc-modified-id="Dropping-extra-rows-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Dropping extra rows</a></span></li></ul></li><li><span><a href="#Export" data-toc-modified-id="Export-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Export</a></span></li></ul></div>

# Import libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import pickle

# Read Data

In [2]:
df = pd.read_csv("Election_Income_Population.csv", index_col=0)
display(df.head())

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
0,1976,"CARTER, JIMMY",659170.0,1182850.0,"FORD, GERALD",504070.0,19610.0,Alabama,NaN,NaN,NaN
1,1976,"CARTER, JIMMY",44058.0,123574.0,"FORD, GERALD",71555.0,7961.0,Alaska,NaN,NaN,NaN
2,1976,"CARTER, JIMMY",295602.0,742719.0,"FORD, GERALD",418642.0,28475.0,Arizona,NaN,NaN,NaN
3,1976,"CARTER, JIMMY",498604.0,767535.0,"FORD, GERALD",267903.0,1028.0,Arkansas,NaN,NaN,NaN
4,1976,"CARTER, JIMMY",3742284.0,7803770.0,"FORD, GERALD",3882244.0,179242.0,California,NaN,NaN,NaN

# Check info and descriptive stats

In [4]:
# descriptive stats
with pd.option_context("float_format", "{:.2f}".format):
    display(df.describe())
    
display(df.info())

,year,Dem_votes,totalvotes,Rep_votes,Third_party_votes,Median income,Standard error,Population
count,715.00,610.00,610.00,610.00,610.00,501.00,501.00,255.00
mean,1998.47,1043355.27,2197409.04,1033059.66,108307.92,60070.20,2100.82,5477930.99
std,13.35,1235830.12,2317454.54,1036050.27,206971.71,10506.13,809.94,6179313.96
min,1976.00,7.00,123574.00,259.00,726.00,36716.00,710.00,401851.00
25%,1988.00,243801.00,603793.50,291093.25,15058.75,52262.00,1525.00,1369944.00
50%,2000.00,649917.00,1487632.00,718659.50,37429.50,58952.00,1961.00,3665228.00
75%,2010.00,1359707.50,2781446.00,1334470.00,105897.25,66360.00,2479.00,6435116.50
max,2020.00,11110250.00,17500881.00,6006429.00,2379822.00,94384.00,6349.00,39538223.00

<class 'pandas.core.frame.DataFrame'>
Int64Index: 715 entries, 0 to 714
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               715 non-null    int64
 1   Dem_candidate      609 non-null    object
 2   Dem_votes          610 non-null    float64
 3   totalvotes         610 non-null    float64
 4   Rep_candidate      610 non-null    object
 5   Rep_votes          610 non-null    float64
 6   Third_party_votes  610 non-null    float64
 7   state              715 non-null    object
 8   Median income      501 non-null    float64
 9   Standard error     501 non-null    float64
 10  Population         255 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 67.0+ KB

None

**Notes:-**

- Dropping rows where median income is null
- Population of closes decade is used for the other years

# Cleaning

## Drop extra rows and clean null values

In [5]:
# Drop null values for Median income
df_new = df.drop(df[df["Median income"].isnull()].index, axis = 0)

In [6]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 501 entries, 99 to 609
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               501 non-null    int64
 1   Dem_candidate      500 non-null    object
 2   Dem_votes          501 non-null    float64
 3   totalvotes         501 non-null    float64
 4   Rep_candidate      501 non-null    object
 5   Rep_votes          501 non-null    float64
 6   Third_party_votes  501 non-null    float64
 7   state              501 non-null    object
 8   Median income      501 non-null    float64
 9   Standard error     501 non-null    float64
 10  Population         100 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 47.0+ KB

In [7]:
# Check the null field for Dem_candidate

df_new[df_new["Dem_candidate"].isnull()]

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
507,2016,NaN,42.0,2573165.0,"TRUMP, DONALD J.",1252401.0,159555.0,Arizona,61592.0,2126.0,NaN

**Notes:-**
    
- We know the candidate this year was Hillary Clinton, so we replace the value with the same

In [8]:
# update the NaN value
df_new.loc[df_new["Dem_candidate"].isnull(), "Dem_candidate"] = "CLINTON, HILLARY"

# check result
df_new.loc[df_new["year"] == 2016, :]

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
504,2016,"CLINTON, HILLARY",729547.0,2123372.0,"TRUMP, DONALD J.",1318255.0,75570.0,Alabama,50936.0,2482.0,NaN
505,2016,"CLINTON, HILLARY",116454.0,318608.0,"TRUMP, DONALD J.",163387.0,38767.0,Alaska,81680.0,4407.0,NaN
506,2016,"CLINTON, HILLARY",1161167.0,2573165.0,"TRUMP, DONALD J.",1252401.0,159555.0,Arizona,61592.0,2126.0,NaN
507,2016,"CLINTON, HILLARY",42.0,2573165.0,"TRUMP, DONALD J.",1252401.0,159555.0,Arizona,61592.0,2126.0,NaN
508,2016,"CLINTON, HILLARY",380494.0,1130635.0,"TRUMP, DONALD J.",684872.0,65269.0,Arkansas,49518.0,2335.0,NaN
509,2016,"CLINTON, HILLARY",8753788.0,14181595.0,"TRUMP, DONALD J.",4483810.0,943997.0,California,71879.0,1160.0,NaN
510,2016,"CLINTON, HILLARY",1338870.0,2780220.0,"TRUMP, DONALD J.",1202484.0,238866.0,Colorado,76117.0,4449.0,NaN
511,2016,"CLINTON, HILLARY",897572.0,1644920.0,"TRUMP, DONALD J.",673215.0,74133.0,Connecticut,81895.0,3672.0,NaN
512,2016,"CLINTON, HILLARY",235603.0,441590.0,"TRUMP, DONALD J.",185127.0,20860.0,Delaware,62612.0,3227.0,NaN
514,2016,"CLINTON, HILLARY",4504975.0,9420039.0,"TRUMP, DONALD J.",4617886.0,297178.0,Florida,55202.0,901.0,NaN
515,2016,"CLINTON, HILLARY",1877963.0,4114732.0,"TRUMP, DONALD J.",2089104.0,147665.0,Georgia,57738.0,1811.0,NaN
516,2016,"CLINTON, HILLARY",266891.0,437664.0,"TRUMP, DONALD J.",128847.0,41926.0,Hawaii,77807.0,2707.0,NaN
517,2016,"CLINTON, HILLARY",189765.0,690255.0,"TRUMP, DONALD J.",409055.0,91435.0,Idaho,61014.0,1360.0,NaN
518,2016,"CLINTON, HILLARY",3090729.0,5536424.0,"TRUMP, DONALD J.",2146015.0,299680.0,Illinois,66215.0,1900.0,NaN
519,2016,"CLINTON, HILLARY",1033126.0,2734958.0,"TRUMP, DONALD J.",1557286.0,144546.0,Indiana,60507.0,3103.0,NaN
520,2016,"CLINTON, HILLARY",653669.0,1565580.0,"TRUMP, DONALD J.",800983.0,110928.0,Iowa,63743.0,2679.0,NaN
521,2016,"CLINTON, HILLARY",427005.0,1184402.0,"TRUMP, DONALD J.",671018.0,86379.0,Kansas,61279.0,3525.0,NaN
522,2016,"CLINTON, HILLARY",628854.0,1924149.0,"TRUMP, DONALD J.",1202971.0,92324.0,Kentucky,48938.0,2163.0,NaN
523,2016,"CLINTON, HILLARY",780154.0,2029032.0,"TRUMP, DONALD J.",1178638.0,70240.0,Louisiana,45515.0,1291.0,NaN
524,2016,"CLINTON, HILLARY",357735.0,771892.0,"TRUMP, DONALD J.",335593.0,78564.0,Maine,54857.0,3609.0,NaN
525,2016,"CLINTON, HILLARY",1677928.0,2781446.0,"TRUMP, DONALD J.",943169.0,160012.0,Maryland,79562.0,2795.0,NaN
526,2016,"CLINTON, HILLARY",1677928.0,2781446.0,"TRUMP, DONALD J.",259.0,160012.0,Maryland,79562.0,2795.0,NaN
527,2016,"CLINTON, HILLARY",78.0,2781446.0,"TRUMP, DONALD J.",943169.0,160012.0,Maryland,79562.0,2795.0,NaN
528,2016,"CLINTON, HILLARY",78.0,2781446.0,"TRUMP, DONALD J.",259.0,160012.0,Maryland,79562.0,2795.0,NaN
529,2016,"CLINTON, HILLARY",1995196.0,3378821.0,"TRUMP, DONALD J.",1090893.0,292732.0,Massachusetts,77951.0,3140.0,NaN
530,2016,"CLINTON, HILLARY",2268839.0,4799284.0,"TRUMP, DONALD J.",2279543.0,250902.0,Michigan,61582.0,2058.0,NaN
531,2016,"CLINTON, HILLARY",1367705.0,2944782.0,"TRUMP, DONALD J.",1322949.0,254128.0,Minnesota,75742.0,4363.0,NaN
532,2016,"CLINTON, HILLARY",485131.0,1209357.0,"TRUMP, DONALD J.",700714.0,23512.0,Mississippi,44332.0,1322.0,NaN
533,2016,"CLINTON, HILLARY",1071068.0,2808605.0,"TRUMP, DONALD J.",1594511.0,143026.0,Missouri,59344.0,1854.0,NaN
534,2016,"CLINTON, HILLARY",177709.0,494526.0,"TRUMP, DONALD J.",279240.0,37577.0,Montana,61565.0,3107.0,NaN
535,2016,"CLINTON, HILLARY",284494.0,844227.0,"TRUMP, DONALD J.",495961.0,63772.0,Nebraska,64045.0,2889.0,NaN
536,2016,"CLINTON, HILLARY",539260.0,1125385.0,"TRUMP, DONALD J.",512058.0,74067.0,Nevada,59791.0,2305.0,NaN
537,2016,"CLINTON, HILLARY",348526.0,744296.0,"TRUMP, DONALD J.",345790.0,49980.0,New Hampshire,82259.0,3142.0,NaN
538,2016,"CLINTON, HILLARY",2148278.0,3874046.0,"TRUMP, DONALD J.",1601933.0,123835.0,New Jersey,73854.0,3093.0,NaN
539,2016,"CLINTON, HILLARY",385234.0,798319.0,"TRUMP, DONALD J.",319667.0,93418.0,New Mexico,52262.0,3194.0,NaN
540,2016,"CLINTON, HILLARY",4379789.0,7802084.0,"TRUMP, DONALD J.",2527142.0,895153.0,New York,66270.0,1516.0,NaN
541,2016,"CLINTON, HILLARY",2189316.0,4741564.0,"TRUMP, DONALD J.",2362631.0,189617.0,North Carolina,57993.0,1757.0,NaN
542,2016,"CLINTON, HILLARY",93758.0,344360.0,"TRUMP, DONALD J.",216794.0,33808.0,North Dakota,64918.0,2470.0,NaN
543,2016,"CLINTON, HILLARY",2394164.0,5496487.0,"TRUMP, DONALD J.",2841005.0,261318.0,Ohio,58232.0,2043.0,NaN
544,2016,"CLINTON, HILLARY",420375.0,1452992.0,"TRUMP, DONALD J.",949136.0,83481.0,Oklahoma,54950.0,1782.0,NaN
545,2016,"CLINTON, HILLARY",1002106.0,2001336.0,"TRUMP, DONALD J.",782403.0,216827.0,Oregon,63787.0,2828.0,NaN
546,2016,"CLINTON, HILLARY",2926441.0,6115402.0,"TRUMP, DONALD J.",2970733.0,218228.0,Pennsylvania,65776.0,2196.0,NaN
547,2016,"CLINTON, HILLARY",252525.0,464144.0,"TRUMP, DONALD J.",180543.0,31076.0,Rhode Island,66368.0,3050.0,NaN
548,2016,"CLINTON, HILLARY",855373.0,2103027.0,"TRUMP, DONALD J.",1155389.0,92265.0,South Carolina,58610.0,3401.0,NaN
549,2016,"CLINTON, HILLARY",117458.0,370093.0,"TRUMP, DONALD J.",227721.0,24914.0,South Dakota,61969.0,3317.0,NaN
550,2016,"CLINTON, HILLARY",870695.0,2508027.0,"TRUMP, DONALD J.",1522925.0,114407.0,Tennessee,55383.0,1496.0,NaN
551,2016,"CLINTON, HILLARY",3877868.0,8969226.0,"TRUMP, DONALD J.",4685047.0,406311.0,Texas,62720.0,1518.0,NaN
552,2016,"CLINTON, HILLARY",310674.0,1131317.0,"TRUMP, DONALD J.",515211.0,305432.0,Utah,72789.0,2413.0,NaN
553,2016,"CLINTON, HILLARY",178573.0,320467.0,"TRUMP, DONALD J.",95369.0,46525.0,Vermont,65623.0,1471.0,NaN
554,2016,"CLINTON, HILLARY",1981473.0,3982752.0,"TRUMP, DONALD J.",1769443.0,231836.0,Virginia,71678.0,2628.0,NaN
555,2016,"CLINTON, HILLARY",1742718.0,3317019.0,"TRUMP, DONALD J.",1221747.0,352554.0,Washington,75841.0,2257.0,NaN
556,2016,"CLINTON, HILLARY",188794.0,713051.0,"TRUMP, DONALD J.",489371.0,34886.0,West Virginia,47843.0,2151.0,NaN
557,2016,"CLINTON, HILLARY",1382536.0,2976150.0,"TRUMP, DONALD J.",1405284.0,188330.0,Wisconsin,64522.0,1990.0,NaN
558,2016,"CLINTON, HILLARY",55973.0,258788.0,"TRUMP, DONALD J.",174419.0,28396.0,Wyoming,62378.0,3368.0,NaN

In [9]:
# check info again for null values
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 501 entries, 99 to 609
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               501 non-null    int64
 1   Dem_candidate      501 non-null    object
 2   Dem_votes          501 non-null    float64
 3   totalvotes         501 non-null    float64
 4   Rep_candidate      501 non-null    object
 5   Rep_votes          501 non-null    float64
 6   Third_party_votes  501 non-null    float64
 7   state              501 non-null    object
 8   Median income      501 non-null    float64
 9   Standard error     501 non-null    float64
 10  Population         100 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 47.0+ KB

## Clean Population data

In [10]:
df_new.year.unique()

array([1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020],
      dtype=int64)

There are only 100 non null values in Population. We first re-check data in the original dataframe

In [11]:
with pd.option_context("display.max_rows", None):
    display(df.loc[df["Median income"].isnull(), :])

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
0,1976,"CARTER, JIMMY",659170.0,1182850.0,"FORD, GERALD",504070.0,19610.0,Alabama,NaN,NaN,NaN
1,1976,"CARTER, JIMMY",44058.0,123574.0,"FORD, GERALD",71555.0,7961.0,Alaska,NaN,NaN,NaN
2,1976,"CARTER, JIMMY",295602.0,742719.0,"FORD, GERALD",418642.0,28475.0,Arizona,NaN,NaN,NaN
3,1976,"CARTER, JIMMY",498604.0,767535.0,"FORD, GERALD",267903.0,1028.0,Arkansas,NaN,NaN,NaN
4,1976,"CARTER, JIMMY",3742284.0,7803770.0,"FORD, GERALD",3882244.0,179242.0,California,NaN,NaN,NaN
5,1976,"CARTER, JIMMY",460801.0,1081440.0,"FORD, GERALD",584278.0,36361.0,Colorado,NaN,NaN,NaN
6,1976,"CARTER, JIMMY",647895.0,1386355.0,"FORD, GERALD",719261.0,19199.0,Connecticut,NaN,NaN,NaN
7,1976,"CARTER, JIMMY",122461.0,235642.0,"FORD, GERALD",109780.0,3401.0,Delaware,NaN,NaN,NaN
8,1976,"CARTER, JIMMY",137818.0,168830.0,"FORD, GERALD",27873.0,3139.0,District Of Columbia,NaN,NaN,NaN
9,1976,"CARTER, JIMMY",1636000.0,3150631.0,"FORD, GERALD",1469531.0,45100.0,Florida,NaN,NaN,NaN
10,1976,"CARTER, JIMMY",147375.0,291301.0,"FORD, GERALD",140003.0,3923.0,Hawaii,NaN,NaN,NaN
11,1976,"CARTER, JIMMY",126549.0,340932.0,"FORD, GERALD",204151.0,10232.0,Idaho,NaN,NaN,NaN
12,1976,"CARTER, JIMMY",2271295.0,4721282.0,"FORD, GERALD",2364269.0,85718.0,Illinois,NaN,NaN,NaN
13,1976,"CARTER, JIMMY",1014714.0,2220362.0,"FORD, GERALD",1183958.0,21690.0,Indiana,NaN,NaN,NaN
14,1976,"CARTER, JIMMY",619931.0,1279303.0,"FORD, GERALD",632864.0,26508.0,Iowa,NaN,NaN,NaN
15,1976,"CARTER, JIMMY",430421.0,957845.0,"FORD, GERALD",502752.0,24672.0,Kansas,NaN,NaN,NaN
16,1976,"CARTER, JIMMY",615717.0,1167142.0,"FORD, GERALD",531852.0,19573.0,Kentucky,NaN,NaN,NaN
17,1976,"CARTER, JIMMY",661365.0,1277383.0,"FORD, GERALD",587446.0,28572.0,Louisiana,NaN,NaN,NaN
18,1976,"CARTER, JIMMY",232279.0,482968.0,"FORD, GERALD",236320.0,14369.0,Maine,NaN,NaN,NaN
19,1976,"CARTER, JIMMY",1429475.0,2547558.0,"FORD, GERALD",1030276.0,87807.0,Massachusetts,NaN,NaN,NaN
20,1976,"CARTER, JIMMY",1696714.0,3651590.0,"FORD, GERALD",1893742.0,61134.0,Michigan,NaN,NaN,NaN
21,1976,"CARTER, JIMMY",1070440.0,1949931.0,"FORD, GERALD",819395.0,60096.0,Minnesota,NaN,NaN,NaN
22,1976,"CARTER, JIMMY",381329.0,768390.0,"FORD, GERALD",366846.0,20215.0,Mississippi,NaN,NaN,NaN
23,1976,"CARTER, JIMMY",998387.0,1953600.0,"FORD, GERALD",927443.0,27770.0,Missouri,NaN,NaN,NaN
24,1976,"CARTER, JIMMY",149259.0,328734.0,"FORD, GERALD",173703.0,5772.0,Montana,NaN,NaN,NaN
25,1976,"CARTER, JIMMY",233293.0,606749.0,"FORD, GERALD",359219.0,14237.0,Nebraska,NaN,NaN,NaN
26,1976,"CARTER, JIMMY",92479.0,201876.0,"FORD, GERALD",101273.0,8124.0,Nevada,NaN,NaN,NaN
27,1976,"CARTER, JIMMY",147645.0,339627.0,"FORD, GERALD",185935.0,6047.0,New Hampshire,NaN,NaN,NaN
28,1976,"CARTER, JIMMY",1444653.0,3014472.0,"FORD, GERALD",1509688.0,60131.0,New Jersey,NaN,NaN,NaN
29,1976,"CARTER, JIMMY",201148.0,416590.0,"FORD, GERALD",211419.0,4023.0,New Mexico,NaN,NaN,NaN
30,1976,"CARTER, JIMMY",3244165.0,6668262.0,"FORD, GERALD",2825913.0,598184.0,New York,NaN,NaN,NaN
31,1976,"CARTER, JIMMY",927365.0,1677906.0,"FORD, GERALD",741960.0,8581.0,North Carolina,NaN,NaN,NaN
32,1976,"CARTER, JIMMY",136078.0,297308.0,"FORD, GERALD",153684.0,7546.0,North Dakota,NaN,NaN,NaN
33,1976,"CARTER, JIMMY",2009959.0,4110456.0,"FORD, GERALD",2000626.0,99871.0,Ohio,NaN,NaN,NaN
34,1976,"CARTER, JIMMY",532442.0,1092251.0,"FORD, GERALD",545708.0,14101.0,Oklahoma,NaN,NaN,NaN
35,1976,"CARTER, JIMMY",490407.0,1029876.0,"FORD, GERALD",492120.0,47349.0,Oregon,NaN,NaN,NaN
36,1976,"CARTER, JIMMY",2328677.0,4620787.0,"FORD, GERALD",2205604.0,86506.0,Pennsylvania,NaN,NaN,NaN
37,1976,"CARTER, JIMMY",227636.0,410584.0,"FORD, GERALD",181249.0,1699.0,Rhode Island,NaN,NaN,NaN
38,1976,"CARTER, JIMMY",450807.0,802583.0,"FORD, GERALD",346149.0,5627.0,South Carolina,NaN,NaN,NaN
39,1976,"CARTER, JIMMY",147068.0,300678.0,"FORD, GERALD",151505.0,2105.0,South Dakota,NaN,NaN,NaN
40,1976,"CARTER, JIMMY",825879.0,1476346.0,"FORD, GERALD",633969.0,16498.0,Tennessee,NaN,NaN,NaN
41,1976,"CARTER, JIMMY",2082319.0,4071884.0,"FORD, GERALD",1953300.0,36265.0,Texas,NaN,NaN,NaN
42,1976,"CARTER, JIMMY",182110.0,541218.0,"FORD, GERALD",337908.0,21200.0,Utah,NaN,NaN,NaN
43,1976,"CARTER, JIMMY",77798.0,183902.0,"FORD, GERALD",100387.0,5717.0,Vermont,NaN,NaN,NaN
44,1976,"CARTER, JIMMY",813896.0,1697094.0,"FORD, GERALD",836554.0,46644.0,Virginia,NaN,NaN,NaN
45,1976,"CARTER, JIMMY",717323.0,1555534.0,"FORD, GERALD",777732.0,60479.0,Washington,NaN,NaN,NaN
46,1976,"CARTER, JIMMY",1040232.0,2101336.0,"FORD, GERALD",1004987.0,56117.0,Wisconsin,NaN,NaN,NaN
47,1976,"CARTER, JIMMY",62239.0,156343.0,"FORD, GERALD",92717.0,1387.0,Wyoming,NaN,NaN,NaN
48,1980,"CARTER, JIMMY",636730.0,1341929.0,"REAGAN, RONALD",654192.0,51007.0,Alabama,NaN,NaN,3893888.0
49,1980,"CARTER, JIMMY",41842.0,158445.0,"REAGAN, RONALD",86112.0,30491.0,Alaska,NaN,NaN,401851.0
50,1980,"CARTER, JIMMY",246843.0,873945.0,"REAGAN, RONALD",529688.0,97414.0,Arizona,NaN,NaN,2718215.0
51,1980,"CARTER, JIMMY",398041.0,837582.0,"REAGAN, RONALD",403164.0,36377.0,Arkansas,NaN,NaN,2286435.0
52,1980,"CARTER, JIMMY",3082943.0,8582938.0,"REAGAN, RONALD",4522994.0,977001.0,California,NaN,NaN,23667902.0
53,1980,"CARTER, JIMMY",368009.0,1184450.0,"REAGAN, RONALD",652264.0,164177.0,Colorado,NaN,NaN,2889964.0
54,1980,"CARTER, JIMMY",541732.0,1406285.0,"REAGAN, RONALD",677210.0,187343.0,Connecticut,NaN,NaN,3107576.0
55,1980,"CARTER, JIMMY",105754.0,235668.0,"REAGAN, RONALD",111252.0,18662.0,Delaware,NaN,NaN,594338.0
56,1980,"CARTER, JIMMY",130231.0,173889.0,"REAGAN, RONALD",23313.0,20345.0,District Of Columbia,NaN,NaN,NaN
57,1980,"CARTER, JIMMY",1419475.0,3686927.0,"REAGAN, RONALD",2046951.0,220501.0,Florida,NaN,NaN,9746324.0
58,1980,"CARTER, JIMMY",890955.0,1596805.0,"REAGAN, RONALD",654168.0,51682.0,Georgia,NaN,NaN,5463105.0
59,1980,"CARTER, JIMMY",135879.0,303287.0,"REAGAN, RONALD",130112.0,37296.0,Hawaii,NaN,NaN,964691.0
60,1980,"CARTER, JIMMY",110192.0,437431.0,"REAGAN, RONALD",290699.0,36540.0,Idaho,NaN,NaN,943935.0
61,1980,"CARTER, JIMMY",1981413.0,4749721.0,"REAGAN, RONALD",2358049.0,410259.0,Illinois,NaN,NaN,11426518.0
62,1980,"CARTER, JIMMY",844197.0,2242033.0,"REAGAN, RONALD",1255656.0,142180.0,Indiana,NaN,NaN,5490224.0
63,1980,"CARTER, JIMMY",508672.0,1317661.0,"REAGAN, RONALD",676026.0,132963.0,Iowa,NaN,NaN,2913808.0
64,1980,"CARTER, JIMMY",326150.0,979795.0,"REAGAN, RONALD",566812.0,86833.0,Kansas,NaN,NaN,2363679.0
65,1980,"CARTER, JIMMY",617417.0,1295627.0,"REAGAN, RONALD",635274.0,42936.0,Kentucky,NaN,NaN,3660777.0
66,1980,"CARTER, JIMMY",708453.0,1548591.0,"REAGAN, RONALD",792853.0,47285.0,Louisiana,NaN,NaN,4205900.0
67,1980,"CARTER, JIMMY",220974.0,523011.0,"REAGAN, RONALD",238522.0,63515.0,Maine,NaN,NaN,1124660.0
68,1980,"CARTER, JIMMY",726161.0,1540496.0,"REAGAN, RONALD",680606.0,133729.0,Maryland,NaN,NaN,4216975.0
69,1980,"CARTER, JIMMY",1053802.0,2524090.0,"REAGAN, RONALD",1057631.0,412657.0,Massachusetts,NaN,NaN,5737037.0
70,1980,"CARTER, JIMMY",1661532.0,3909725.0,"REAGAN, RONALD",1915225.0,332968.0,Michigan,NaN,NaN,9262078.0
71,1980,"CARTER, JIMMY",954173.0,2051916.0,"REAGAN, RONALD",873268.0,224475.0,Minnesota,NaN,NaN,4075970.0
72,1980,"CARTER, JIMMY",429281.0,891750.0,"REAGAN, RONALD",441089.0,21380.0,Mississippi,NaN,NaN,2520638.0
73,1980,"CARTER, JIMMY",931182.0,2099824.0,"REAGAN, RONALD",1074181.0,94461.0,Missouri,NaN,NaN,4916686.0
74,1980,"CARTER, JIMMY",118032.0,363952.0,"REAGAN, RONALD",206814.0,39106.0,Montana,NaN,NaN,786690.0
75,1980,"CARTER, JIMMY",166424.0,639533.0,"REAGAN, RONALD",419214.0,53895.0,Nebraska,NaN,NaN,1569825.0
76,1980,"CARTER, JIMMY",66666.0,243692.0,"REAGAN, RONALD",155017.0,22009.0,Nevada,NaN,NaN,800493.0
77,1980,"CARTER, JIMMY",108864.0,383990.0,"REAGAN, RONALD",221705.0,53421.0,New Hampshire,NaN,NaN,920610.0
78,1980,"CARTER, JIMMY",1147364.0,2975684.0,"REAGAN, RONALD",1546557.0,281763.0,New Jersey,NaN,NaN,7364823.0
79,1980,"CARTER, JIMMY",167826.0,456237.0,"REAGAN, RONALD",250779.0,37632.0,New Mexico,NaN,NaN,1302894.0
80,1980,"CARTER, JIMMY",2728372.0,6201959.0,"REAGAN, RONALD",2637700.0,835887.0,New York,NaN,NaN,17558072.0
81,1980,"CARTER, JIMMY",875635.0,1855833.0,"REAGAN, RONALD",915018.0,65180.0,North Carolina,NaN,NaN,5881766.0
82,1980,"CARTER, JIMMY",79189.0,301116.0,"REAGAN, RONALD",193695.0,28232.0,North Dakota,NaN,NaN,652717.0
83,1980,"CARTER, JIMMY",1752414.0,4283603.0,"REAGAN, RONALD",2206545.0,324644.0,Ohio,NaN,NaN,10797630.0
84,1980,"CARTER, JIMMY",402026.0,1149708.0,"REAGAN, RONALD",695570.0,52112.0,Oklahoma,NaN,NaN,3025290.0
85,1980,"CARTER, JIMMY",456890.0,1181516.0,"REAGAN, RONALD",571044.0,153582.0,Oregon,NaN,NaN,2633105.0
86,1980,"CARTER, JIMMY",1937540.0,4561501.0,"REAGAN, RONALD",2261872.0,362089.0,Pennsylvania,NaN,NaN,11863895.0
87,1980,"CARTER, JIMMY",198342.0,415967.0,"REAGAN, RONALD",154793.0,62832.0,Rhode Island,NaN,NaN,947154.0
88,1980,"CARTER, JIMMY",428220.0,888258.0,"REAGAN, RONALD",439277.0,20761.0,South Carolina,NaN,NaN,3121820.0
89,1980,"CARTER, JIMMY",103855.0,327703.0,"REAGAN, RONALD",198343.0,25505.0,South Dakota,NaN,NaN,690768.0
90,1980,"CARTER, JIMMY",783051.0,1617616.0,"REAGAN, RONALD",787761.0,46804.0,Tennessee,NaN,NaN,4591120.0
91,1980,"CARTER, JIMMY",1881147.0,4541636.0,"REAGAN, RONALD",2510705.0,149784.0,Texas,NaN,NaN,14229191.0
92,1980,"CARTER, JIMMY",124266.0,604152.0,"REAGAN, RONALD",439687.0,40199.0,Utah,NaN,NaN,1461037.0
93,1980,"CARTER, JIMMY",81952.0,213299.0,"REAGAN, RONALD",94628.0,36719.0,Vermont,NaN,NaN,511456.0
94,1980,"CARTER, JIMMY",752174.0,1866032.0,"REAGAN, RONALD",989609.0,124249.0,Virginia,NaN,NaN,5346818.0
95,1980,"CARTER, JIMMY",650193.0,1742394.0,"REAGAN, RONALD",865244.0,226957.0,Washington,NaN,NaN,4132156.0
96,1980,"CARTER, JIMMY",367462.0,737715.0,"REAGAN, RONALD",334206.0,36047.0,West Virginia,NaN,NaN,1949644.0
97,1980,"CARTER, JIMMY",981584.0,2273221.0,"REAGAN, RONALD",1088845.0,202792.0,Wisconsin,NaN,NaN,4705767.0
98,1980,"CARTER, JIMMY",49427.0,176713.0,"REAGAN, RONALD",110700.0,16586.0,Wyoming,NaN,NaN,469557.0
107,1984,"MONDALE, WALTER",180408.0,211288.0,"REAGAN, RONALD",29009.0,1871.0,District Of Columbia,NaN,NaN,NaN
157,1988,"DUKAKIS, MICHAEL",159407.0,192877.0,"BUSH, GEORGE H.W.",27590.0,5880.0,District Of Columbia,NaN,NaN,NaN
208,1992,"CLINTON, BILL",192619.0,227572.0,"BUSH, GEORGE H.W.",20698.0,14255.0,District Of Columbia,NaN,NaN,NaN
259,1996,"CLINTON, BILL",158220.0,185726.0,"DOLE, ROBERT",17339.0,10167.0,District Of Columbia,NaN,NaN,NaN
310,2000,"GORE, AL",171923.0,201894.0,"BUSH, GEORGE W.",18073.0,11898.0,District Of Columbia,NaN,NaN,NaN
361,2004,"KERRY, JOHN",202970.0,227586.0,"BUSH, GEORGE W.",21256.0,3360.0,District Of Columbia,NaN,NaN,NaN
412,2008,"OBAMA, BARACK H.",245800.0,265853.0,"MCCAIN, JOHN",17367.0,2686.0,District Of Columbia,NaN,NaN,NaN
462,2012,"OBAMA, BARACK H.",267070.0,293764.0,"ROMNEY, MITT",21381.0,5313.0,District Of Columbia,NaN,NaN,NaN
513,2016,"CLINTON, HILLARY",282830.0,312575.0,"TRUMP, DONALD J.",12723.0,17022.0,District Of Columbia,NaN,NaN,NaN
567,2020,"BIDEN, JOSEPH R. JR",317323.0,344356.0,"TRUMP, DONALD J.",18586.0,8447.0,District Of Columbia,NaN,NaN,NaN
610,2020,NaN,NaN,NaN,NaN,NaN,NaN,District of Columbia,NaN,NaN,689545.0
611,2010,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,NaN,NaN,4779736.0
612,2010,NaN,NaN,NaN,NaN,NaN,NaN,Alaska,NaN,NaN,710231.0
613,2010,NaN,NaN,NaN,NaN,NaN,NaN,Arizona,NaN,NaN,6392017.0
614,2010,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,NaN,NaN,2915918.0
615,2010,NaN,NaN,NaN,NaN,NaN,NaN,California,NaN,NaN,37253956.0
616,2010,NaN,NaN,NaN,NaN,NaN,NaN,Colorado,NaN,NaN,5029196.0
617,2010,NaN,NaN,NaN,NaN,NaN,NaN,Connecticut,NaN,NaN,3574097.0
618,2010,NaN,NaN,NaN,NaN,NaN,NaN,Delaware,NaN,NaN,897934.0
619,2010,NaN,NaN,NaN,NaN,NaN,NaN,District of Columbia,NaN,NaN,601723.0
620,2010,NaN,NaN,NaN,NaN,NaN,NaN,Florida,NaN,NaN,18801310.0
621,2010,NaN,NaN,NaN,NaN,NaN,NaN,Georgia,NaN,NaN,9687653.0
622,2010,NaN,NaN,NaN,NaN,NaN,NaN,Hawaii,NaN,NaN,1360301.0
623,2010,NaN,NaN,NaN,NaN,NaN,NaN,Idaho,NaN,NaN,1567582.0
624,2010,NaN,NaN,NaN,NaN,NaN,NaN,Illinois,NaN,NaN,12830632.0
625,2010,NaN,NaN,NaN,NaN,NaN,NaN,Indiana,NaN,NaN,6483802.0
626,2010,NaN,NaN,NaN,NaN,NaN,NaN,Iowa,NaN,NaN,3046355.0
627,2010,NaN,NaN,NaN,NaN,NaN,NaN,Kansas,NaN,NaN,2853118.0
628,2010,NaN,NaN,NaN,NaN,NaN,NaN,Kentucky,NaN,NaN,4339367.0
629,2010,NaN,NaN,NaN,NaN,NaN,NaN,Louisiana,NaN,NaN,4533372.0
630,2010,NaN,NaN,NaN,NaN,NaN,NaN,Maine,NaN,NaN,1328361.0
631,2010,NaN,NaN,NaN,NaN,NaN,NaN,Maryland,NaN,NaN,5773552.0
632,2010,NaN,NaN,NaN,NaN,NaN,NaN,Massachusetts,NaN,NaN,6547629.0
633,2010,NaN,NaN,NaN,NaN,NaN,NaN,Michigan,NaN,NaN,9883640.0
634,2010,NaN,NaN,NaN,NaN,NaN,NaN,Minnesota,NaN,NaN,5303925.0
635,2010,NaN,NaN,NaN,NaN,NaN,NaN,Mississippi,NaN,NaN,2967297.0
636,2010,NaN,NaN,NaN,NaN,NaN,NaN,Missouri,NaN,NaN,5988927.0
637,2010,NaN,NaN,NaN,NaN,NaN,NaN,Montana,NaN,NaN,989415.0
638,2010,NaN,NaN,NaN,NaN,NaN,NaN,Nebraska,NaN,NaN,1826341.0
639,2010,NaN,NaN,NaN,NaN,NaN,NaN,Nevada,NaN,NaN,2700551.0
640,2010,NaN,NaN,NaN,NaN,NaN,NaN,New Hampshire,NaN,NaN,1316470.0
641,2010,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,NaN,NaN,8791894.0
642,2010,NaN,NaN,NaN,NaN,NaN,NaN,New Mexico,NaN,NaN,2059179.0
643,2010,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN,NaN,19378102.0
644,2010,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,NaN,NaN,9535483.0
645,2010,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,NaN,NaN,672591.0
646,2010,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,NaN,NaN,11536504.0
647,2010,NaN,NaN,NaN,NaN,NaN,NaN,Oklahoma,NaN,NaN,3751351.0
648,2010,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,NaN,NaN,3831074.0
649,2010,NaN,NaN,NaN,NaN,NaN,NaN,Pennsylvania,NaN,NaN,12702379.0
650,2010,NaN,NaN,NaN,NaN,NaN,NaN,Rhode Island,NaN,NaN,1052567.0
651,2010,NaN,NaN,NaN,NaN,NaN,NaN,South Carolina,NaN,NaN,4625364.0
652,2010,NaN,NaN,NaN,NaN,NaN,NaN,South Dakota,NaN,NaN,814180.0
653,2010,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee,NaN,NaN,6346105.0
654,2010,NaN,NaN,NaN,NaN,NaN,NaN,Texas,NaN,NaN,25145561.0
655,2010,NaN,NaN,NaN,NaN,NaN,NaN,Utah,NaN,NaN,2763885.0
656,2010,NaN,NaN,NaN,NaN,NaN,NaN,Vermont,NaN,NaN,625741.0
657,2010,NaN,NaN,NaN,NaN,NaN,NaN,Virginia,NaN,NaN,8001024.0
658,2010,NaN,NaN,NaN,NaN,NaN,NaN,Washington,NaN,NaN,6724540.0
659,2010,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia,NaN,NaN,1852994.0
660,2010,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,NaN,NaN,5686986.0
661,2010,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,NaN,NaN,563626.0
662,2000,NaN,NaN,NaN,NaN,NaN,NaN,District of Columbia,NaN,NaN,572059.0
663,1990,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,NaN,NaN,4040587.0
664,1990,NaN,NaN,NaN,NaN,NaN,NaN,Alaska,NaN,NaN,550043.0
665,1990,NaN,NaN,NaN,NaN,NaN,NaN,Arizona,NaN,NaN,3665228.0
666,1990,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,NaN,NaN,2350725.0
667,1990,NaN,NaN,NaN,NaN,NaN,NaN,California,NaN,NaN,29760021.0
668,1990,NaN,NaN,NaN,NaN,NaN,NaN,Colorado,NaN,NaN,3294394.0
669,1990,NaN,NaN,NaN,NaN,NaN,NaN,Connecticut,NaN,NaN,3287116.0
670,1990,NaN,NaN,NaN,NaN,NaN,NaN,Delaware,NaN,NaN,666168.0
671,1990,NaN,NaN,NaN,NaN,NaN,NaN,District of Columbia,NaN,NaN,606900.0
672,1990,NaN,NaN,NaN,NaN,NaN,NaN,Florida,NaN,NaN,12937926.0
673,1990,NaN,NaN,NaN,NaN,NaN,NaN,Georgia,NaN,NaN,6478216.0
674,1990,NaN,NaN,NaN,NaN,NaN,NaN,Hawaii,NaN,NaN,1108229.0
675,1990,NaN,NaN,NaN,NaN,NaN,NaN,Idaho,NaN,NaN,1006749.0
676,1990,NaN,NaN,NaN,NaN,NaN,NaN,Illinois,NaN,NaN,11430602.0
677,1990,NaN,NaN,NaN,NaN,NaN,NaN,Indiana,NaN,NaN,5544159.0
678,1990,NaN,NaN,NaN,NaN,NaN,NaN,Iowa,NaN,NaN,2776755.0
679,1990,NaN,NaN,NaN,NaN,NaN,NaN,Kansas,NaN,NaN,2477574.0
680,1990,NaN,NaN,NaN,NaN,NaN,NaN,Kentucky,NaN,NaN,3685296.0
681,1990,NaN,NaN,NaN,NaN,NaN,NaN,Louisiana,NaN,NaN,4219973.0
682,1990,NaN,NaN,NaN,NaN,NaN,NaN,Maine,NaN,NaN,1227928.0
683,1990,NaN,NaN,NaN,NaN,NaN,NaN,Maryland,NaN,NaN,4781468.0
684,1990,NaN,NaN,NaN,NaN,NaN,NaN,Massachusetts,NaN,NaN,6016425.0
685,1990,NaN,NaN,NaN,NaN,NaN,NaN,Michigan,NaN,NaN,9295297.0
686,1990,NaN,NaN,NaN,NaN,NaN,NaN,Minnesota,NaN,NaN,4375099.0
687,1990,NaN,NaN,NaN,NaN,NaN,NaN,Mississippi,NaN,NaN,2573216.0
688,1990,NaN,NaN,NaN,NaN,NaN,NaN,Missouri,NaN,NaN,5117073.0
689,1990,NaN,NaN,NaN,NaN,NaN,NaN,Montana,NaN,NaN,799065.0
690,1990,NaN,NaN,NaN,NaN,NaN,NaN,Nebraska,NaN,NaN,1578385.0
691,1990,NaN,NaN,NaN,NaN,NaN,NaN,Nevada,NaN,NaN,1201833.0
692,1990,NaN,NaN,NaN,NaN,NaN,NaN,New Hampshire,NaN,NaN,1109252.0
693,1990,NaN,NaN,NaN,NaN,NaN,NaN,New Jersey,NaN,NaN,7730188.0
694,1990,NaN,NaN,NaN,NaN,NaN,NaN,New Mexico,NaN,NaN,1515069.0
695,1990,NaN,NaN,NaN,NaN,NaN,NaN,New York,NaN,NaN,17990455.0
696,1990,NaN,NaN,NaN,NaN,NaN,NaN,North Carolina,NaN,NaN,6628637.0
697,1990,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,NaN,NaN,638800.0
698,1990,NaN,NaN,NaN,NaN,NaN,NaN,Ohio,NaN,NaN,10847115.0
699,1990,NaN,NaN,NaN,NaN,NaN,NaN,Oklahoma,NaN,NaN,3145585.0
700,1990,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,NaN,NaN,2842321.0
701,1990,NaN,NaN,NaN,NaN,NaN,NaN,Pennsylvania,NaN,NaN,11881643.0
702,1990,NaN,NaN,NaN,NaN,NaN,NaN,Rhode Island,NaN,NaN,1003464.0
703,1990,NaN,NaN,NaN,NaN,NaN,NaN,South Carolina,NaN,NaN,3486703.0
704,1990,NaN,NaN,NaN,NaN,NaN,NaN,South Dakota,NaN,NaN,696004.0
705,1990,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee,NaN,NaN,4877185.0
706,1990,NaN,NaN,NaN,NaN,NaN,NaN,Texas,NaN,NaN,16986510.0
707,1990,NaN,NaN,NaN,NaN,NaN,NaN,Utah,NaN,NaN,1722850.0
708,1990,NaN,NaN,NaN,NaN,NaN,NaN,Vermont,NaN,NaN,562758.0
709,1990,NaN,NaN,NaN,NaN,NaN,NaN,Virginia,NaN,NaN,6187358.0
710,1990,NaN,NaN,NaN,NaN,NaN,NaN,Washington,NaN,NaN,4866692.0
711,1990,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia,NaN,NaN,1793477.0
712,1990,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,NaN,NaN,4891769.0
713,1990,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,NaN,NaN,453588.0
714,1980,NaN,NaN,NaN,NaN,NaN,NaN,District of Columbia,NaN,NaN,638333.0

**Observation**:-
    
- No Income values present before 1984 and at non election years: 1980, 1990, 2010
- Values are also not present for a specific state: District of Columbia. Since DC comes under Washington and we have a data value for this state, we can drop these rows as well
- Therefore, we can drop all above columns. Thus, we have already correctly cleaned some of our population data. Cleaning the rest of null values now

In [12]:
# Define function

def get_population(df_current, df_population):
    
    # Create copies of dataframes moving ahead
    df_elec = df_current.copy()
    df_pop = df_population.copy()

    ## get unique years in our new (cleaned) election dataset
    year_elec = df_elec["year"].unique()
    
    
    for i in year_elec:
        
        ## get the last digit for each year, then choose closest 1000s year
        if i%10 < 5:
            year = i - i%10
        else:
            year = i + 10 - i%10

        ## create dataframes to merge
        df1 = df_elec.loc[df_elec["year"] == i, ["year","state"]]
        df2 = df_pop.loc[df_pop["year"] == year, ["year", "state", "Population"]]

        #display(df1)
        #display(df2)

        ## left join to get new population
        df_merged = pd.merge(df1, df2, on = "state", how = "left", suffixes = ("_x", "_y"))
        #display(df_merged)

        ## change index for replacement
        df_merged = df_merged.set_index(df_elec.loc[df_elec["year"] == i, "Population"].index)

        ## now replace rows in df_elec
        df_elec.loc[df_elec["year"] == i, "Population"] = df_merged["Population"]

       
    return df_elec

In [13]:
# get new cleaned dataset
df_clean = get_population(df_new, df)

In [14]:
# View cleaned dataframe info
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 501 entries, 99 to 609
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               501 non-null    int64
 1   Dem_candidate      501 non-null    object
 2   Dem_votes          501 non-null    float64
 3   totalvotes         501 non-null    float64
 4   Rep_candidate      501 non-null    object
 5   Rep_votes          501 non-null    float64
 6   Third_party_votes  501 non-null    float64
 7   state              501 non-null    object
 8   Median income      501 non-null    float64
 9   Standard error     501 non-null    float64
 10  Population         501 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 47.0+ KB

Thus, there are no null values present now

## Data type cleaning

We assign correct data types to certain columns

In [15]:
# change dtype of year to category
df_clean["year"] = df_clean["year"].astype("category")

# change object types to category
for col in df_clean.select_dtypes("object").columns:
    df_clean[col] = df_clean[col].astype("category")

In [16]:
# review
display(df_clean.head())
display(df_clean.info())
with pd.option_context("float_format", "{:.2f}".format):
    display(df_clean.describe())

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
99,1984,"MONDALE, WALTER",551899.0,1441713.0,"REAGAN, RONALD",872849.0,16965.0,Alabama,41190.0,1440.0,3893888.0
100,1984,"MONDALE, WALTER",62007.0,207605.0,"REAGAN, RONALD",138377.0,7221.0,Alaska,76992.0,3505.0,401851.0
101,1984,"MONDALE, WALTER",333854.0,1025897.0,"REAGAN, RONALD",681416.0,10627.0,Arizona,50981.0,1449.0,2718215.0
102,1984,"MONDALE, WALTER",338646.0,884406.0,"REAGAN, RONALD",534774.0,10986.0,Arkansas,37297.0,1780.0,2286435.0
103,1984,"MONDALE, WALTER",3922519.0,9505041.0,"REAGAN, RONALD",5467009.0,115513.0,California,60171.0,866.0,23667902.0

<class 'pandas.core.frame.DataFrame'>
Int64Index: 501 entries, 99 to 609
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               501 non-null    category
 1   Dem_candidate      501 non-null    category
 2   Dem_votes          501 non-null    float64
 3   totalvotes         501 non-null    float64
 4   Rep_candidate      501 non-null    category
 5   Rep_votes          501 non-null    float64
 6   Third_party_votes  501 non-null    float64
 7   state              501 non-null    category
 8   Median income      501 non-null    float64
 9   Standard error     501 non-null    float64
 10  Population         501 non-null    float64
dtypes: category(4), float64(7)
memory usage: 36.8 KB

None

,Dem_votes,totalvotes,Rep_votes,Third_party_votes,Median income,Standard error,Population
count,501.00,501.00,501.00,501.00,501.00,501.00,501.00
mean,1118326.61,2342323.04,1095648.64,112901.52,60070.20,2100.82,5703751.85
std,1306764.77,2410767.79,1065375.67,216960.09,10506.13,809.94,6304017.99
min,7.00,176551.00,259.00,726.00,36716.00,710.00,401851.00
25%,266348.00,670438.00,331237.00,15303.00,52262.00,1525.00,1569825.00
50%,690080.00,1617700.00,769044.00,37625.00,58952.00,1961.00,4012012.00
75%,1454742.00,2944782.00,1405284.00,110702.00,66360.00,2479.00,6628637.00
max,11110250.00,17500881.00,6006429.00,2379822.00,94384.00,6349.00,39538223.00

## Dropping extra rows

In [22]:
df_clean[df_clean["state"] == "Maryland"]

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
119,1984,"MONDALE, WALTER",787935.0,1675873.0,"REAGAN, RONALD",879918.0,8020.0,Maryland,70691.0,2739.0,4216975.0
169,1988,"DUKAKIS, MICHAEL",826304.0,1714358.0,"BUSH, GEORGE H.W.",876167.0,11887.0,Maryland,77109.0,2523.0,4781468.0
220,1992,"CLINTON, BILL",988571.0,1984580.0,"BUSH, GEORGE H.W.",707094.0,288915.0,Maryland,67468.0,2949.0,4781468.0
271,1996,"CLINTON, BILL",966207.0,1780870.0,"DOLE, ROBERT",681530.0,133133.0,Maryland,72504.0,4227.0,5296486.0
322,2000,"GORE, AL",1144008.0,2025212.0,"BUSH, GEORGE W.",813827.0,67377.0,Maryland,82201.0,2110.0,5296486.0
373,2004,"KERRY, JOHN",1334493.0,2384238.0,"BUSH, GEORGE W.",1024703.0,25035.0,Maryland,78442.0,2324.0,5296486.0
374,2004,OTHER,7.0,2384238.0,"BUSH, GEORGE W.",1024703.0,25035.0,Maryland,78442.0,2324.0,5296486.0
424,2008,"OBAMA, BARACK H.",1629467.0,2631596.0,"MCCAIN, JOHN",959862.0,42267.0,Maryland,76784.0,2132.0,5773552.0
474,2012,"OBAMA, BARACK H.",1677844.0,2707327.0,"ROMNEY, MITT",971869.0,57614.0,Maryland,81137.0,2091.0,5773552.0
525,2016,"CLINTON, HILLARY",1677928.0,2781446.0,"TRUMP, DONALD J.",943169.0,160012.0,Maryland,79562.0,2795.0,6177224.0
526,2016,"CLINTON, HILLARY",1677928.0,2781446.0,"TRUMP, DONALD J.",259.0,160012.0,Maryland,79562.0,2795.0,6177224.0
527,2016,"CLINTON, HILLARY",78.0,2781446.0,"TRUMP, DONALD J.",943169.0,160012.0,Maryland,79562.0,2795.0,6177224.0
528,2016,"CLINTON, HILLARY",78.0,2781446.0,"TRUMP, DONALD J.",259.0,160012.0,Maryland,79562.0,2795.0,6177224.0
579,2020,"BIDEN, JOSEPH R. JR",1985023.0,3037030.0,"TRUMP, DONALD J.",976414.0,75593.0,Maryland,94384.0,4208.0,6177224.0

In [23]:
df_clean[df_clean["state"] == "Arizona"]

,year,Dem_candidate,Dem_votes,totalvotes,Rep_candidate,Rep_votes,Third_party_votes,state,Median income,Standard error,Population
101,1984,"MONDALE, WALTER",333854.0,1025897.0,"REAGAN, RONALD",681416.0,10627.0,Arizona,50981.0,1449.0,2718215.0
151,1988,"DUKAKIS, MICHAEL",454029.0,1171873.0,"BUSH, GEORGE H.W.",702541.0,15303.0,Arizona,55767.0,1778.0,3665228.0
202,1992,"CLINTON, BILL",543050.0,1486975.0,"BUSH, GEORGE H.W.",572086.0,371839.0,Arizona,53241.0,1973.0,3665228.0
253,1996,"CLINTON, BILL",653288.0,1404405.0,"DOLE, ROBERT",622073.0,129044.0,Arizona,52140.0,2100.0,5130632.0
304,2000,"GORE, AL",685341.0,1532016.0,"BUSH, GEORGE W.",781652.0,65023.0,Arizona,59966.0,1824.0,5130632.0
355,2004,"KERRY, JOHN",893524.0,2012585.0,"BUSH, GEORGE W.",1104294.0,14767.0,Arizona,60231.0,1570.0,5130632.0
406,2008,"OBAMA, BARACK H.",1034707.0,2293475.0,"MCCAIN, JOHN",1230111.0,28657.0,Arizona,56540.0,1356.0,6392017.0
456,2012,"OBAMA, BARACK H.",1025232.0,2299254.0,"ROMNEY, MITT",1233654.0,40368.0,Arizona,53135.0,3300.0,6392017.0
506,2016,"CLINTON, HILLARY",1161167.0,2573165.0,"TRUMP, DONALD J.",1252401.0,159555.0,Arizona,61592.0,2126.0,7151502.0
507,2016,"CLINTON, HILLARY",42.0,2573165.0,"TRUMP, DONALD J.",1252401.0,159555.0,Arizona,61592.0,2126.0,7151502.0
561,2020,"BIDEN, JOSEPH R. JR",1672143.0,3387326.0,"TRUMP, DONALD J.",1661686.0,53497.0,Arizona,66628.0,3534.0,7151502.0

In [ ]:
indices_to_drop = [374, 526, 527, 528, 507]

In [18]:
df_clean.drop(index = indices_to_drop, inplace = True)

In [19]:
df_clean.state.value_counts()

Maryland          14
Arizona           11
Alabama           10
Pennsylvania      10
Nevada            10
New Hampshire     10
New Jersey        10
New Mexico        10
New York          10
North Carolina    10
North Dakota      10
Ohio              10
Oregon            10
Rhode Island      10
Alaska            10
South Carolina    10
South Dakota      10
Tennessee         10
Texas             10
Utah              10
Vermont           10
Virginia          10
West Virginia     10
Wisconsin         10
Nebraska          10
Montana           10
Illinois          10
Mississippi       10
Arkansas          10
California        10
Colorado          10
Connecticut       10
Delaware          10
Florida           10
Georgia           10
Hawaii            10
Idaho             10
Wyoming           10
Kentucky          10
Maine             10
Massachusetts     10
Michigan          10
Minnesota         10
Indiana            9
Iowa               9
Kansas             9
Louisiana          9
Washington         9
Missouri           9
Oklahoma           7
Name: state, dtype: int64

Thus, we have cleaned our dataset

# Export

We export files as pickle and csv

In [ ]:
# Export to csv

df_clean.to_csv("dataset_cleaned.csv", index = False)

In [ ]:
# export as pickle file

object_filename = "df_clean.sav"

saved_object = pickle.dump(df_clean, open(object_filename,'wb'))

print('Dataframe is saved into to disk successfully Using Pickle')

In [ ]:
# to retrieve the file use:-

file = open("df_clean.sav",'rb')
df_clean = pickle.load(file)
file.close()

In [ ]:
df_clean.year.value_counts()